# Generated by Django 3.2.5 on 2021-12-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_eventplan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='category',
            field=models.CharField(default='その他', max_length=30),
        ),
        migrations.AlterField(
            model_name='plan',
            name='help',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='plan',
            name='outline',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='plan',
            name='person',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='target',
            field=models.CharField(default='誰でも', max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='time',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='plan',
            name='tools',
            field=models.CharField(default='', max_length=100),
        ),
    ]
